[package]
name = "bevy_aoui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "^0.12", default-features = false, features = ["bevy_sprite", "bevy_text"] }
itertools = "^0.11"


[features]
default = ["bundles"]
## Enable alternative versions of bevy's sprite, spritesheet and text bundles.
bundles = []

[dev-dependencies]
bevy_egui = "0.23"
rand = "0.8.5"
bevy = { version = "^0.12" }

